const USER_FETCH_MESSAGES_REQUEST = 'USER_FETCH_MESSAGES_REQUEST'
const USER_FETCH_MESSAGES_SUCCESS = 'USER_FETCH_MESSAGES_SUCCESS'
const USER_FETCH_MESSAGES_FAILURE = 'USER_FETCH_MESSAGES_FAILURE'

export {USER_FETCH_MESSAGES_REQUEST, USER_FETCH_MESSAGES_SUCCESS, USER_FETCH_MESSAGES_FAILURE}
